version: "3"
services:
  spring-yml:
    image: api-spring-image
    ports:
      - "8082:8082"
    networks:
      - data-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - data-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=ramkishore0202#
      - MYSQL_DATABASE=rmkshr

networks:
  data-network: